name: partseg

channels:
  - pytorch
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - pip
  - cudatoolkit=10.2
  - pytorch=1.8.1
  - torchvision=0.9.1
  - openblas-devel
  - k3d
  - msgpack-python
  - pip:
      - -r requirements.txt
