transforms:
  - _target_: src.datamodules.transforms.ToTensor
    expand_dims: false
  - _target_: src.datamodules.transforms.MapInstancesToSemanticLabels
    labels_mapping: map_1800_1
    mapping_file: /code/data/mappings/all_mappings_v4.csv
    mapped_key: "semantic"
    labels_key: "mask"
    map_bg_to_value: -1
  - _target_: src.datamodules.transforms.NormalizeInstanceLabels
    instance_label_key: "object"
  - _target_: src.datamodules.transforms.PrepareSparseFeatures
    keys_to_sparsify: ['semantic', 'object', 'object_size']
    nnz_key: 'object'
    add_color: true
    bg_value: 0
  - _target_: src.datamodules.transforms.ComputeInstanceMasks
    instance_mask: "object"