transforms:
  - _target_: src.datamodules.transforms.ToTensor
    expand_dims: false
  - _target_: src.datamodules.transforms.MapInstancesToSemanticLabels
    labels_mapping: map_1800_1
    mapping_file: /code/data/mappings/all_mappings_v4.csv
    mapped_key: "semantic"
    labels_key: "mask"
    map_bg_to_value: -1
  - _target_: src.datamodules.transforms.PrepareSparseFeatures
    keys_to_sparsify: ['semantic']
    nnz_key: 'semantic'
    add_color: true
    bg_value: 0