defaults:
  - default.yaml

log_confusion_matrix:
  _target_: src.callbacks.metric_callbacks.LogConfusionMatrixAndMetrics
  label_names: /code/data/label_names/map_1800_1.csv
  plot_3d_points_every_n: 16
  head_id: 0
  semantic_key: 'semantic'
test_semseg_callback:
  _target_: src.callbacks.metric_callbacks.TestingSemSeg
  label_names: /code/data/label_names/map_1800_1.csv
  plot_3d_points_every_n: 50
