_target_: src.datamodules.scannet_datamodule.ScannetDataModule

data_dir: "/scannet/scannet-voxelized-sdf"
#data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
num_workers: 6
limit: null
pin_memory: True
val_split_ratio: 0.05
labels_mapping: map_1800_1
train_file: /code/data/split/train.optim.csv
mapping_file: /code/data/mappings/all_mappings_v3.csv
transforms:
#  - _target_: src.datamodules.transforms.RandomFlip
#    axes: [1, 2]
#  - _target_: src.datamodules.transforms.RandomRotate90
#    axes: [1, 2]
#  - _target_: src.datamodules.transforms.RandomRotate
#    axes: [[2, 1]]
#  - _target_: src.datamodules.transforms.ElasticDeformation
#    execution_probability: 0.3
  - _target_: src.datamodules.transforms.ToTensor
    expand_dims: false
  - _target_: src.datamodules.transforms.MapInstancesToSemanticLabels
    labels_mapping: map_1800_1
    mapping_file: /code/data/mappings/all_mappings_v3.csv
    mapped_key: "semantic"
    sparse: True
  - _target_: src.datamodules.transforms.NormalizeInstanceLabels
    instance_label_key: "objects"
  - _target_: src.datamodules.transforms.ToSparse
    semantic_key: "semantic"
    instance_key: "objects"
    bg_value: 0
  - _target_: src.datamodules.transforms.ComputeInstanceMasks
    max_num_of_instances_in_sample: 40
    instance_mask: "objects"