_target_: src.datamodules.scannet_datamodule.ScannetDataModule

data_dir: "/scannet/scannet-voxelized-sdf"
#data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 8
num_workers: 6
limit: 64
pin_memory: True
num_val_samples: 32
train_file: /code/data/split/train.optim.csv